import { Document, Page, Text, View, StyleSheet } from '@react-pdf/renderer'
import type { UserProfile } from '@/lib/types'
import type { PeakWeekDay } from '@/lib/peak-week'

const GOLD = '#c9a84c'
const DARK = '#0d0d0d'
const CARD = '#1a1a1a'
const BORDER = '#2a2a2a'
const MUTED = '#888888'
const FOREGROUND = '#f0f0f0'

const styles = StyleSheet.create({
  page: { backgroundColor: DARK, color: FOREGROUND, padding: 28, fontSize: 9, fontFamily: 'Helvetica' },
  headerTitle: { fontSize: 20, color: GOLD, fontFamily: 'Helvetica-Bold', letterSpacing: 1 },
  headerSub: { fontSize: 9, color: MUTED, marginTop: 2 },
  dayHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 8, marginTop: 18, borderTopWidth: 2, borderTopColor: GOLD, paddingTop: 8 },
  dayLabel: { fontSize: 14, color: GOLD, fontFamily: 'Helvetica-Bold', letterSpacing: 0.5 },
  dayNote: { fontSize: 8, color: MUTED },
  targetRow: { flexDirection: 'row', gap: 6, marginBottom: 8 },
  targetBox: { flex: 1, backgroundColor: CARD, borderWidth: 1, borderColor: BORDER, padding: 6, alignItems: 'center' },
  targetLabel: { fontSize: 6, color: MUTED, letterSpacing: 0.5 },
  targetValue: { fontSize: 11, color: GOLD, fontFamily: 'Helvetica-Bold', marginTop: 2 },
  noteRow: { flexDirection: 'row', gap: 12, marginBottom: 6 },
  noteText: { fontSize: 8, color: MUTED },
  mealBlock: { marginBottom: 6 },
  mealName: { fontSize: 9, color: FOREGROUND, fontFamily: 'Helvetica-Bold', marginBottom: 2 },
  foodRow: { flexDirection: 'row', justifyContent: 'space-between', paddingVertical: 1.5, borderBottomWidth: 0.5, borderBottomColor: BORDER },
  foodName: { fontSize: 8, color: FOREGROUND },
  foodDetail: { fontSize: 7, color: MUTED },
  footer: { position: 'absolute', bottom: 20, left: 28, right: 28, fontSize: 6.5, color: MUTED, textAlign: 'center' },
})

export function PeakWeekPDF({
  profile,
  protocol,
  showDate,
}: {
  profile: UserProfile
  protocol: PeakWeekDay[]
  showDate: string
}) {
  const showDateLabel = new Date(showDate + 'T12:00:00').toLocaleDateString('en-AU', { day: 'numeric', month: 'long', year: 'numeric' })

  return (
    <Document>
      {protocol.map(day => (
        <Page key={day.daysOut} size="A4" style={styles.page}>
          <View>
            <Text style={styles.headerTitle}>ATHLETIC ODYSSEY — PEAK WEEK PROTOCOL</Text>
            <Text style={styles.headerSub}>{profile.name} · Show Day: {showDateLabel}</Text>
          </View>

          <View style={styles.dayHeader}>
            <Text style={styles.dayLabel}>{day.label}</Text>
            <Text style={styles.dayNote}>Training: {day.targets.trainingNote}   ·   Cardio: {day.targets.cardioNote}</Text>
          </View>

          <View style={styles.targetRow}>
            <View style={styles.targetBox}><Text style={styles.targetLabel}>KCAL</Text><Text style={styles.targetValue}>{day.targets.calories}</Text></View>
            <View style={styles.targetBox}><Text style={styles.targetLabel}>PROTEIN</Text><Text style={styles.targetValue}>{day.targets.protein}g</Text></View>
            <View style={styles.targetBox}><Text style={styles.targetLabel}>CARBS</Text><Text style={styles.targetValue}>{day.targets.carbs}g</Text></View>
            <View style={styles.targetBox}><Text style={styles.targetLabel}>FATS</Text><Text style={styles.targetValue}>{day.targets.fats}g</Text></View>
          </View>

          <View style={styles.noteRow}>
            <Text style={styles.noteText}>Sodium: ×{day.targets.sodiumMultiplier} vs normal</Text>
            <Text style={styles.noteText}>Fibre target: {day.targets.fibreTarget}</Text>
            <Text style={styles.noteText}>Water: {day.targets.waterTarget}</Text>
          </View>

          {day.mealPlan.meals.map(meal => (
            <View key={meal.id} style={styles.mealBlock} wrap={false}>
              <Text style={styles.mealName}>{meal.name.toUpperCase()} — {meal.totals.calories} kcal</Text>
              {meal.foods.map((food, idx) => (
                <View key={idx} style={styles.foodRow}>
                  <Text style={styles.foodName}>{food.name} — {food.servingSize}{food.servingUnit}</Text>
                  <Text style={styles.foodDetail}>{food.macros.calories}kcal · {food.macros.protein}p · {food.macros.carbs}c · {food.macros.fats}f</Text>
                </View>
              ))}
            </View>
          ))}

          <Text style={styles.footer} fixed>
            Generated by Athletic Odyssey — Elite Performance Tracker. Targets follow the Norton/Baker peak week protocol. Adjust with your coach if anything feels off.
          </Text>
        </Page>
      ))}
    </Document>
  )
}
